id: A29974824
title: Magnetizing (Wangdü) Prayer
type: translation
pechas:
- I50B5744F
- IA22D33AC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:27:12.207963
  last_modified_at: 2023-01-04 11:27:12.207974
  collections:
  - Adeu Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I50B5744F/C818: A88A
  IA22D33AC/BDB6: A88A
